XDROID_HOST_TIME := $(shell date +"%Y%m%d-%H%M")
XDROID_BUILD_DATE := $(shell date -u +%d%m%Y)
XDROID_BUILD_TIME := $(shell date -u +%H%M)
XDROID_BUILD_DATE_TIME := $(XDROID_BUILD_DATE)$(XDROID_BUILD_TIME)

ifndef XDROID_BUILD_TYPE
   XDROID_BUILD_TYPE := REL
endif

XDROID_VERSION := 17
XDROID_ANDROID := 14.0
XDROID_VERSION_PLATFORM := $(XDROID_ANDROID).$(XDROID_VERSION)
XDROID_PLATFORM_RELEASE_OR_CODENAME := 14.0
XDROID_REVISION := INA.XD.$(XDROID_ANDROID).$(XDROID_VERSION)-$(XDROID_BUILD)-$(XDROID_BUILD_DATE)-$(XDROID_BUILD_TIME)-$(XDROID_BUILD_TYPE)
XDROID_BUILD_NUMBER := XD.r$(XDROID_VERSION).$(XDROID_HOST_TIME)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
   ro.aosp.revision=$(AOSP_REVISION) \
   ro.xdroid.fullver=$(XDROID_VERSION_PLATFORM) \
   ro.xdroid.platform_release_or_codename=$(XDROID_PLATFORM_RELEASE_OR_CODENAME) \
   ro.xdroid.revision=$(XDROID_REVISION) \
   ro.xdroid.build.security_patch=$(XDROID_SECURITY_PATCH) \
   ro.xdroid.build.number=$(XDROID_BUILD_NUMBER) \
   ro.build.datetime=$(XDROID_BUILD_DATE_TIME)